### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by NKID00** [Fallen-Breath/Fallen-Breath.github.io#1]
https://github.com/Fallen-Breath/Fallen-Breath.github.io/blob/eafc61f6f76aaec21c4ccbbbe4a4b4f9fba1fd62/2020/09/17/deeply-dissecting-minecraft_3.4/index.html#L475

该标签为真时二极管*熄灭* -> 该标签为真时二极管**亮起**

**Comment by Fallen-Breath** [comment]
fixed in 97441ef018f9713666db83c72a613684686d9b0a
